import { useState, type ReactNode } from 'react'
import { ArrowDown, ArrowRight, CalendarDays, Check, Clock3, MapPin, Menu, Phone, Quote, X } from 'lucide-react'
import { blog, business, faqs, footerContent, hero, navigation, pricing, sectionContent, services, socialLinks, therapist } from './config'
import { trackEvent } from './analytics'

const ConfigHeading = ({ lines }: { lines: readonly string[] }) => <>{lines[0]}<br/><em>{lines[1]}</em></>
const BookButton = ({ className = '' }: { className?: string }) => <a className={`button ${className}`} href={business.bookingUrl} target="_blank" rel="noreferrer" onClick={() => trackEvent('book_appointment')}>{hero.primaryCta} <ArrowRight size={17}/></a>
const SectionHeading = ({ eyebrow, title, intro }: { eyebrow: string; title: readonly string[]; intro?: string }) => <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2><ConfigHeading lines={title}/></h2></div>{intro && <p>{intro}</p>}</div>

function Header() {
  const [open, setOpen] = useState(false)
  return <header className="header"><a className="brand" href="#top" aria-label={`${business.name} home`}><span className="brand-mark">{business.name[0]}</span><span>{business.name}<small>{business.category}</small></span></a><button className="nav-toggle" onClick={() => setOpen(!open)} aria-expanded={open} aria-label="Toggle menu">{open ? <X/> : <Menu/>}</button><nav className={open ? 'nav open' : 'nav'} aria-label="Main navigation">{navigation.map(item => <a href={item.href} key={item.href} onClick={() => setOpen(false)}>{item.label}</a>)}<BookButton className="nav-book"/></nav></header>
}

function Hero() { return <section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">{hero.eyebrow}</p><h1><ConfigHeading lines={hero.title}/></h1><p className="hero-text">{hero.description}</p><div className="hero-actions"><BookButton/><a className="text-link" href="#services">{hero.secondaryCta} <ArrowDown size={16}/></a></div><div className="trust">{hero.trustItems.map(item => <span key={item}><Check/> {item}</span>)}</div></div><div className="hero-art" aria-label={hero.artworkLabel}><div className="sun"/><div className="arch"><div className="plant"><i/><i/><i/><b/></div><div className="table"><span/><b/></div></div><p>{hero.quote.map((line, index) => <span key={line}>{line}{index === 0 && <br/>}</span>)}</p></div></section> }

function Services() { const copy = sectionContent.services; return <section className="section services" id="services"><SectionHeading eyebrow={copy.eyebrow} title={copy.title} intro={copy.intro}/><div className="service-grid">{services.map((service, index) => <article className="service-card" key={service.title}><span className="service-number">0{index + 1}</span><h3>{service.title}</h3><p>{service.description}</p><small>{copy.bestForLabel}</small><strong>{service.bestFor}</strong><a href={business.bookingUrl} onClick={() => trackEvent('service_click', service.title)} target="_blank" rel="noreferrer" aria-label={`${copy.cta}: ${service.title}`}>{copy.cta} <ArrowRight size={16}/></a></article>)}</div></section> }

function Pricing() { return <section className="pricing" id="pricing"><div className="pricing-intro"><p className="eyebrow light">{pricing.eyebrow}</p><h2><ConfigHeading lines={pricing.title}/></h2><p>{pricing.description}</p><div className="note"><Clock3/><span>{pricing.helpTitle}<br/><a href={`mailto:${business.email}`} onClick={() => trackEvent('contact')}>{pricing.helpCta}</a></span></div></div><div className="price-list">{pricing.sessions.map(session => <article className={'featured' in session && session.featured ? 'featured' : ''} key={session.minutes}>{'featured' in session && session.featured && <span className="popular">{pricing.popularLabel}</span>}<div><span className="minutes">{session.minutes}<small>{pricing.durationUnit}</small></span><span><h3>{session.name}</h3><p>{session.description}</p></span></div><div><strong>{session.price}</strong><a href={business.bookingUrl} target="_blank" rel="noreferrer" onClick={() => trackEvent('pricing_click', String(session.minutes))}>{pricing.reserveCta} <ArrowRight size={16}/></a></div></article>)}</div></section> }

function Bio() { return <section className="section bio" id="about"><div className="portrait"><div className="portrait-art"><span>{therapist.initials}</span><i/></div><div className="experience"><strong>{therapist.yearsInPractice}</strong><span>{therapist.experienceLabel[0]}<br/>{therapist.experienceLabel[1]}</span></div></div><div className="bio-copy"><p className="eyebrow">{therapist.eyebrow}</p><h2>{therapist.heading}</h2><h3>{therapist.philosophy}</h3>{therapist.biography.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<blockquote><Quote/><span>{therapist.quote}</span></blockquote><div className="certs">{therapist.certifications.map(item => <span key={item}><Check/> {item}</span>)}</div></div></section> }

function FAQ() { const copy = sectionContent.faq; return <section className="section faq" id="faq"><div><p className="eyebrow">{copy.eyebrow}</p><h2><ConfigHeading lines={copy.title}/></h2><p>{copy.prompt}</p><a href={`mailto:${business.email}`}>{copy.cta} <ArrowRight size={16}/></a></div><div className="accordion">{faqs.map((item, index) => <details key={item.question} open={index === 0}><summary>{item.question}<span>+</span></summary><p>{item.answer}</p></details>)}</div></section> }

function BookingCTA() { const copy = sectionContent.booking; return <section className="booking"><div><CalendarDays/><p className="eyebrow light">{copy.eyebrow}</p><h2><ConfigHeading lines={copy.title}/></h2><p>{copy.description}</p><BookButton className="cream"/><small>{copy.questionText} <a href={`tel:${business.phoneHref}`}>Call {business.phone}</a></small></div></section> }

function BlogPreview() { return <section className="section journal"><SectionHeading eyebrow={blog.eyebrow} title={blog.title} intro={blog.intro}/><div className="post-grid">{blog.posts.map(post => <article key={post.title}><div className={`post-art art-${post.number}`}><span>{post.number}</span></div><small>{post.category}</small><h3>{post.title}</h3><a href={post.href} aria-label={`${blog.cta}: ${post.title}`}>{blog.cta} <ArrowRight size={15}/></a></article>)}</div></section> }

function Contact() { const copy = sectionContent.contact; return <section className="contact" id="contact"><div className="map-card"><div className="map-lines"/><MapPin/><span>{business.name}</span><small>{business.location}</small></div><div className="contact-copy"><p className="eyebrow">{copy.eyebrow}</p><h2><ConfigHeading lines={copy.title}/></h2><div className="contact-item"><MapPin/><span><small>{copy.locationLabel}</small>{business.address}<em>{business.appointmentNote}</em></span></div><div className="contact-item"><Phone/><span><small>{copy.contactLabel}</small><a href={`tel:${business.phoneHref}`}>{business.phone}</a><a href={`mailto:${business.email}`}>{business.email}</a></span></div><div className="contact-item"><Clock3/><span><small>{copy.hoursLabel}</small>{business.hours.map(hour => <span key={hour}>{hour}</span>)}</span></div><BookButton/></div></section> }

function LinkGroup({ label, links }: { label: string; links: readonly { label: string; href: string }[] }) { return <div><small>{label}</small>{links.map(link => <a href={link.href} key={link.label}>{link.label}</a>)}</div> }
function Footer() { return <footer><div className="footer-brand"><div className="brand"><span className="brand-mark">{business.name[0]}</span><span>{business.name}<small>{business.category}</small></span></div><p>{business.tagline}</p></div><LinkGroup {...footerContent.groups.explore}/><div><small>{footerContent.connectLabel}</small>{socialLinks.map(link => <a href={link.href} key={link.label}>{link.label}</a>)}<a href={`mailto:${business.email}`}>{footerContent.emailLabel}</a><a href={`tel:${business.phoneHref}`}>{footerContent.phoneLabel}</a></div><LinkGroup {...footerContent.groups.legal}/><div className="copyright">© {new Date().getFullYear()} {business.name}. {footerContent.copyrightSuffix}<span>{business.footerNote}</span></div></footer> }

export default function App(): ReactNode { return <><Header/><main><Hero/><Services/><Pricing/><Bio/><BookingCTA/><FAQ/><BlogPreview/><Contact/></main><Footer/></> }
